### ISSUE TITLE
Webpanel mobile layout is buggy

### ISSUE THREAD

**Issue by olokos** [kerberos-io/agent#69]
![image](https://user-images.githubusercontent.com/1755581/218598111-f0f3fd1b-2ece-442f-8fb0-28a57e5891d6.png)

Also, it's impossible to hide the sidebar, tapping on it does nothing and this makes the website hard to use on mobile if not impossible, without switching to PC mode.

**Comment by cedricve** [comment]
Thanks for reporting definitely some work needed ;)

**Comment by olokos** [comment]
Really looking forward to seeing a fix for this, I think just making the left sidebar hamburger actually work as it should on mobile, should fix this.

**Comment by cedricve** [comment]
This should be fixed by https://github.com/kerberos-io/agent/commit/71cd315142a97f56596bfe3b56a3c5aadb45d592

![Screenshot 2023-03-21 at 15 19 20](https://user-images.githubusercontent.com/1546779/226666139-4515a5a9-df64-4f46-be6d-ab7b0c5c385d.png)

![Screenshot 2023-03-21 at 15 19 25](https://user-images.githubusercontent.com/1546779/226666194-8a484cf6-251b-4b2e-9473-a4abaccaec0e.png)
